### ISSUE TITLE
Do you want to take over el_finder officially?

### ISSUE THREAD

**Issue by phallstrom** [nikolaifedorov/el_finder#14]
Hi -

Seems like you've been busy on el_finder.  I haven't been able to get to it.

Do you want to take it over officially?

**Comment by nikolaifedorov** [comment]
Hi, Philip.
The first, short story about my fork.

I use el_finder gem in RoR project. :)
I need more functionality than was in your code.
For this reason, I have made fork from you. After some modifies, I did refactoring code.

Also currently I have DRAFT version el_finder for FTP, Dropbox.
I can read structure storages (show files and folders).

I think that I will have some special things (for example EJB-connection for special storage). This approach can be used in JRuby.

I will continue to add changes as it will needed.

About officially.
If some people will be to improve current code then i will glad and I can control 'pull request' from them.

What do you mean about 'take it over officially'?

**Comment by phallstrom** [comment]
I can transfer my repository to you, or update it's README to point to you.  You'd need to take the rubygem as well I suppose.

I'm also happy merging in your work if you'd rather do that.  I just don't have as much time as I thought I would to keep working on it as I'd like.   I want to, just don't right now.

No need to make a decision, just thought I'd see...
